[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Maps/Archipelago.Archipelago
EditorStartupMap=/Game/Maps/Archipelago.Archipelago
GlobalDefaultGameMode=/Script/Explored.ExploredGameMode

[/Script/Engine.RendererSettings]
r.DefaultFeature.AutoExposure=True
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Lumen.TraceMeshSDFs=1
r.GenerateMeshDistanceFields=True
r.Shadow.Virtual.Enable=1
r.AntiAliasingMethod=4
r.Nanite.ProjectEnabled=True
r.VolumetricFog=1
r.SkinCache.CompileShaders=True
r.RayTracing=False
r.CustomDepth=3
r.AllowStaticLighting=False
r.Substrate=False

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/Explored")
GameUserSettingsClassName=/Script/Explored.ExploredGameUserSettings

[/Script/PythonScriptPlugin.PythonScriptPluginSettings]
bDeveloperMode=True

[Core.Log]
LogExplored=Log

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=64FB0B03435264919920E3B9FB3715C9
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=


[ConsoleVariables]
; Importador FBX clásico: respeta las opciones de color de vértice de los scripts de importación.
Interchange.FeatureFlags.Import.FBX=False
